#!/bin/sh
# Create Deck Project Directories

SCRIPT_NAME="deck_setup.sh"
SCRIPT_AUTHOR="Danya D. Smith"
SCRIPT_UPDATED="Tuesday, December 26, 2023 3:34 AM"

echo "Executing: $SCRIPT_NAME"
echo "By: $SCRIPT_AUTHOR"
echo "Last Updated: $SCRIPT_UPDATED"

echo "Adding Folders"
mkdir 00-front-matter
mkdir 01-tarot-atramento
mkdir 02-tarot-chromati
mkdir 03-summa-esoterica
mkdir 04-tarot-esoterica
mkdir 05-summa-chromati
mkdir 06-tarot-meditatio
mkdir 07-tarot-kabbalah
mkdir 08-summa-kabbalah
mkdir 09-tarot-pictura
mkdir 10-waite-smith-tarot

mkdir 00-front-matter/pocket
mkdir 00-front-matter/poker

tree -d


