#!/bin/sh
# Create Deck Project Directories

SCRIPT_NAME="deck_setup.sh"
SCRIPT_AUTHOR="Danya D. Smith"
SCRIPT_UPDATED="Sunday 02 May 2021 @ 6:35 PM"

echo "Executing: $SCRIPT_NAME"
echo "By: $SCRIPT_AUTHOR"
echo "Last Updated: $SCRIPT_UPDATED"

echo "Adding Folders"
mkdir 00-front-matter
mkdir 01-smith-waite-tarot-chromati
mkdir 02-tarot-esoterica
mkdir 03-summa-esoterica
mkdir 04-summa-chromati
mkdir 05-smith-waite-tarot-atramento

tree -d


