#!/bin/sh
# Install and Configure Zsh

SCRIPT_NAME="install_zsh.sh"
SCRIPT_AUTHOR="Danya D. Smith"
SCRIPT_UPDATED="Saturday 22 August 2020 @ 7:20 PM"

echo "Executing: $SCRIPT_NAME"
echo "By: $SCRIPT_AUTHOR"
echo "Last Updated: $SCRIPT_UPDATED"

echo "Install oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Install typewritten"
npm install -g typewritten

echo "Install zsh-syntax-highlighting"
brew install zsh-syntax-highlighting


