#!/bin/sh
# Install and Configure Zsh

SCRIPT_NAME="install_brews.sh"
SCRIPT_AUTHOR="Danya D. Smith"
SCRIPT_UPDATED="Saturday 22 August 2020 @ 7:20 PM"

echo "Executing: $SCRIPT_NAME"
echo "By: $SCRIPT_AUTHOR"
echo "Last Updated: $SCRIPT_UPDATED"

echo "Install Homebrew Packages"

brew install atk
brew install autoconf
brew install automake
brew install cairo
brew install czmq
brew install diff-so-fancy
brew install figlet
brew install fontconfig
brew install fontforge
brew install freetype
brew install fribidi
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install gh
brew install giflib
brew install glib
brew install gobject-introspection
brew install graphite2
brew install gsettings-desktop-schemas
brew install gtk+3
brew install harfbuzz
brew install hicolor-icon-theme
brew install icu4c
brew install jpeg
brew install krb5
brew install libepoxy
brew install libevent
brew install libffi
brew install libpng
brew install libspiro
brew install libtiff
brew install libtool
brew install libuninameslist
brew install lzo
brew install ncurses
brew install openssl@1.1
brew install pango
brew install pcre
brew install pixman
brew install pkg-config
brew install postgresql
brew install python@3.8
brew install readline
brew install sqlite
brew install tmux
brew install trash
brew install tree
brew install utf8proc
brew install watch
brew install xz
brew install zeromq
brew install zsh-syntax-highlighting
