#!/bin/sh
# Set Hotfix User Secrets

SCRIPT_NAME="set-hotfix-user-secrets.sh"
SCRIPT_AUTHOR="Danya D. Smith"
SCRIPT_UPDATED="Monday 22 January 2024 @ 3:39 PM"

echo "Executing: $SCRIPT_NAME"
echo "By: $SCRIPT_AUTHOR"
echo "Last Updated: $SCRIPT_UPDATED"


echo ""
echo "-------------------------------------------------------------------------"
echo "Navigate to Achieve.Web"
echo "-------------------------------------------------------------------------"
echo ""

cd /Users/danyadsmith/Development/Projects/triskelle/IDOE/Achieve.Web

dotnet user-secrets set ConnectionStrings:DefaultConnection 'Server=idoe.database.usgovcloudapi.net;Initial Catalog=idoe-production_2024-04-11T15-19Z;Persist Security Info=False;User ID=idoe-achieve;Password=Ekz9ZE!7;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;'

dotnet user-secrets set ConnectionStrings:DataConnection 'Server=idoe.database.usgovcloudapi.net;Initial Catalog=idoe-production_2024-04-11T15-19Z;Persist Security Info=False;User ID=idoe-achieve;Password=Ekz9ZE!7;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;'

dotnet user-secrets set SurveyManagerSettings:ConnectionString 'Server=idoe.database.usgovcloudapi.net;Initial Catalog=idoe-production_2024-04-11T15-19Z;Persist Security Info=False;User ID=idoe-achieve;Password=Ekz9ZE!7;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;'

echo ""
echo "-------------------------------------------------------------------------"
echo "Confirm User Secrets"
echo "-------------------------------------------------------------------------"
echo ""

dotnet user-secrets list | grep Connection



