#!/bin/sh
# Set Local User Secrets

SCRIPT_NAME="set-local-user-secrets.sh"
SCRIPT_AUTHOR="Danya D. Smith"
SCRIPT_UPDATED="Monday 18 December 2023 @ 12:24 PM"

echo "Executing: $SCRIPT_NAME"
echo "By: $SCRIPT_AUTHOR"
echo "Last Updated: $SCRIPT_UPDATED"

echo ""
echo "-------------------------------------------------------------------------"
echo "Navigate to Achieve.Web"
echo "-------------------------------------------------------------------------"
echo ""

cd /Users/danyadsmith/Development/Projects/triskelle/IDOE/Achieve.Web

dotnet user-secrets set ConnectionStrings:DefaultConnection 'Server=localhost;Database=Achieve;Trusted_Connection=False;User Id=sa;Password=Manlike!Dora12unclasp34snowy5;Encrypt=false;TrustServerCertificate=true;'

dotnet user-secrets set ConnectionStrings:DataConnection 'Server=localhost;Database=Achieve;Trusted_Connection=False;User Id=sa;Password=Manlike!Dora12unclasp34snowy5;Encrypt=false;TrustServerCertificate=true;'

dotnet user-secrets set SurveyManagerSettings:ConnectionString 'Server=localhost;Database=Achieve;Trusted_Connection=False;User Id=sa;Password=Manlike!Dora12unclasp34snowy5;Encrypt=false;TrustServerCertificate=true;'


echo ""
echo "-------------------------------------------------------------------------"
echo "Confirm User Secrets"
echo "-------------------------------------------------------------------------"
echo ""

dotnet user-secrets list | grep Connection


