#!/bin/sh
# Setup Vim and Neovim Configuration

SCRIPT_NAME="vim_setup.sh"
SCRIPT_AUTHOR="Danya D. Smith"
SCRIPT_UPDATED="Friday 17 August 2018 @ 6:54 PM"

echo "Executing: $SCRIPT_NAME"
echo "By: $SCRIPT_AUTHOR"
echo "Last Updated: $SCRIPT_UPDATED"

echo "Adding .vimrc"
trash ~/.vimrc
ln -s ~/Development/Configuration/dotfiles/vim/Main/.vimrc ~/.vimrc

echo "Adding .gvimrc"
trash ~/.gvimrc
ln -s ~/Development/Configuration/dotfiles/vim/Main/.gvimrc ~/.gvimrc

echo "Creating Directory: ~/.vim/autoload"
trash ~/.vim/autoload
mkdir ~/.vim/autoload
ln -s ~/Development/Configuration/dotfiles/vim/Main/pathogen.vim ~/.vim/autoload/pathogen.vim

echo "Deleting Directory: ~/.vim/bundle"
trash ~/.vim/bundle

echo "Creating Directory: ~/.vim/pack/plugins/start"
mkdir ~/.vim/pack
cd ~/.vim/pack
mkdir plugins
cd plugins
mkdir start
cd start

echo "========================================================================="
echo ""

echo "Cloning Plugins into ~/.vim/pack/plugins/start"

echo "Installing Plugin: base16-vim"
git clone https://github.com/chriskempson/base16-vim
echo "========================================================================="
echo ""

echo "Installing Plugin: calendar.vim"
git clone https://github.com/itchyny/calendar.vim
echo "========================================================================="
echo ""

echo "Installing Plugin: ctrlp"
git clone https://github.com/kien/ctrlp.vim.git
echo "========================================================================="
echo ""

echo "Installing Plugin: drawit"
git clone https://github.com/vim-scripts/DrawIt
echo "========================================================================="
echo ""

echo "Installing Plugin: emmet-vim"
git clone https://github.com/mattn/emmet-vim.git
echo "========================================================================="
echo ""

echo "Installing Plugin: lightline"
git clone https://github.com/danyadsmith/lightline.vim
echo "========================================================================="
echo ""

echo "Installing Plugin: my-vim-snippets"
git clone https://github.com/danyadsmith/my-vim-snippets
echo "========================================================================="
echo ""

echo "Installing Plugin: tabular"
git clone https://github.com/godlygeek/tabular
echo "========================================================================="
echo ""

echo "Installing Plugin: TagHighlight"
git clone https://github.com/vim-scripts/TagHighlight
echo "========================================================================="
echo ""

echo "Installing Plugin: Typescript-Vim"
git clone https://github.com/leafgarland/typescript-vim
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-anotherkolor"
git clone https://github.com/danyadsmith/vim-anotherkolor.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-commentary"
git clone https://github.com/tpope/vim-commentary
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-csharp"
git clone https://github.com/OrangeT/vim-csharp.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-fugitive"
git clone https://github.com/tpope/vim-fugitive
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-gitbranch"
git clone https://github.com/itchyny/vim-gitbranch
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-gitgutter"
git clone https://github.com/airblade/vim-gitgutter
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-HiLinkTrace"
git clone https://github.com/gerw/vim-HiLinkTrace.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-javascript"
git clone https://github.com/pangloss/vim-javascript.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-js-pretty-template"
git clone https://github.com/Quramy/vim-js-pretty-template
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-markdown-enhancements"
git clone https://github.com/mattly/vim-markdown-enhancements
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-marked"
git clone https://github.com/itspriddle/vim-marked.git 
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-minisnip"
git clone https://github.com/joereynolds/vim-minisnip
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-repeat"
git clone https://github.com/tpope/vim-repeat.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-surround"
git clone https://github.com/tpope/vim-surround.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-unimpaired"
git clone http://github.com/tpope/vim-unimpaired.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vimwiki"
git clone https://github.com/vimwiki/vimwiki
echo "========================================================================="
echo ""

echo "Installing Plugin: typescript-vim"
git clone https://github.com/leafgarland/typescript-vim.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-json"
git clone https://github.com/elzr/vim-json.git
echo "========================================================================="
echo ""

echo "Installing Plugin: UniCycle"
git clone https://github.com/vim-scripts/UniCycle
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-textobj-user"
git clone https://github.com/kana/vim-textobj-user.git
echo "========================================================================="
echo ""

echo "Installing Plugin: vim-textobj-quote"
git clone https://github.com/reedes/vim-textobj-quote.git
echo "========================================================================="
echo ""

echo "Creating Directory: ~/.vim/pack/plugins/opt"
cd ~/.vim/pack/plugins
mkdir opt
cd opt

echo "Installing Plugin: vim-coloresque"
git clone https://github.com/Marslo/vim-coloresque.git
echo "========================================================================="
echo ""

echo "Finished installing plugins and colorschemes."
echo ""

echo "Creating Directory: ~/.vim/after"
mkdir ~/.vim/after
mkdir ~/.vim/after/ftplugin
echo "Symlinking: ~/.vim/after files"
ln -s ~/Development/Configuration/dotfiles/vim/Main/after/ftplugin/cs.vim ~/.vim/after/ftplugin/cs.vim
ln -s ~/Development/Configuration/dotfiles/vim/Main/after/ftplugin/typescript.vim ~/.vim/after/ftplugin/typescript.vim
echo ""

echo "Creating Directory: ~/.vim/colors"
mkdir ~/.vim/colors
ln -s ~/Development/Configuration/dotfiles/vim/Main/colors/demo_light.vim ~/.vim/colors/demo_light.vim
echo ""

echo "Configuring NeoVim"
trash ~/.config/nvim/init.vim
ln -s ~/Development/Configuration/dotfiles/vim/Main/.vimrc ~/.config/nvim/init.vim
trash ~/.config/nvim/ginit.vim
ln -s ~/Development/Configuration/dotfiles/vim/Main/ginit.vim ~/.config/nvim/ginit.vim
ln -s ~/.vim/bundle ~/.config/nvim/
ln -s ~/.vim/autoload ~/.config/nvim/
ln -s ~/.vim/colors ~/.config/nvim/
echo ""


